resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: local-registry:5000/mapproxy-operator
  newTag: v0.0.39

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  - certs/ca.crt
  name: operator-certificates
